// Seed all static match and ranking data into Postgres.
// Uses INSERT ... ON CONFLICT (id) DO UPDATE for matches.
// Uses DELETE + INSERT for rankings (serial IDs, no natural key).

export async function seed(pool) {
  await seedMatches(pool);
  await seedRankings(pool);
  console.log('Seed complete.');
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function upsertMatch(pool, m) {
  await pool.query(
    `INSERT INTO matches (
       id, gender, match_date, round, status, start_time,
       home_name, home_rank, home_record, home_logo, home_conference,
       away_name, away_rank, away_record, away_logo, away_conference,
       home_score, away_score, winner, stats_url, results_url, updated_at
     ) VALUES (
       $1,$2,$3,$4,$5,$6,
       $7,$8,$9,$10,$11,
       $12,$13,$14,$15,$16,
       $17,$18,$19,$20,$21,NOW()
     )
     ON CONFLICT (id) DO UPDATE SET
       gender         = EXCLUDED.gender,
       match_date     = EXCLUDED.match_date,
       round          = EXCLUDED.round,
       status         = EXCLUDED.status,
       start_time     = EXCLUDED.start_time,
       home_name      = EXCLUDED.home_name,
       home_rank      = EXCLUDED.home_rank,
       home_record    = EXCLUDED.home_record,
       home_logo      = EXCLUDED.home_logo,
       home_conference= EXCLUDED.home_conference,
       away_name      = EXCLUDED.away_name,
       away_rank      = EXCLUDED.away_rank,
       away_record    = EXCLUDED.away_record,
       away_logo      = EXCLUDED.away_logo,
       away_conference= EXCLUDED.away_conference,
       home_score     = EXCLUDED.home_score,
       away_score     = EXCLUDED.away_score,
       winner         = EXCLUDED.winner,
       stats_url      = EXCLUDED.stats_url,
       results_url    = EXCLUDED.results_url,
       updated_at     = NOW()`,
    [
      m.id, m.gender, m.match_date, m.round ?? null, m.status, m.start_time ?? null,
      m.home_name, m.home_rank ?? null, m.home_record ?? null, m.home_logo ?? null, m.home_conference ?? null,
      m.away_name, m.away_rank ?? null, m.away_record ?? null, m.away_logo ?? null, m.away_conference ?? null,
      m.home_score ?? 0, m.away_score ?? 0, m.winner ?? null,
      m.stats_url ?? null, m.results_url ?? null,
    ]
  );
}

// ---------------------------------------------------------------------------
// Matches
// ---------------------------------------------------------------------------

async function seedMatches(pool) {
  // ── Men's Today (Apr 15, 2026) ──────────────────────────────────────────
  const menToday = [
    {
      id: 'live-3',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'SEC Championship — R1',
      status: 'final',
      home_name: 'Kentucky',
      home_rank: 26,
      home_record: '16-12',
      home_logo: '🐱',
      home_conference: 'SEC',
      away_name: 'Arkansas',
      away_rank: 36,
      away_record: '16-13',
      away_logo: '🐗',
      away_conference: 'SEC',
      home_score: 3,
      away_score: 2,
      winner: 'home',
      stats_url: 'https://stats.statbroadcast.com/broadcast/?id=658013',
      results_url: null,
    },
    {
      id: 'live-1',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'SEC Championship — R1',
      status: 'final',
      home_name: 'Vanderbilt',
      home_rank: 22,
      home_record: '16-11',
      home_logo: '⚓',
      home_conference: 'SEC',
      away_name: 'Alabama',
      away_rank: 50,
      away_record: '12-16',
      away_logo: '🐘',
      away_conference: 'SEC',
      home_score: 0,
      away_score: 0,
      winner: null,
      stats_url: 'https://statb.us/b/658014',
      results_url: null,
    },
    {
      id: 'today-2',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'SEC Championship — R1',
      status: 'final',
      home_name: 'Tennessee',
      home_rank: 56,
      home_record: '10-17',
      home_logo: '🍊',
      home_conference: 'SEC',
      away_name: 'Ole Miss',
      away_rank: 25,
      away_record: '18-8',
      away_logo: '🔴',
      away_conference: 'SEC',
      home_score: 0,
      away_score: 4,
      winner: 'away',
      stats_url: null,
      results_url: 'https://olemisssports.com/news/2026/4/15/mens-tennis-mens-tennis-beats-tennessee-to-advance-to-second-round-of-sec-tournament',
    },
    {
      id: 'today-4',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Boston College',
      home_rank: null,
      home_record: null,
      home_logo: '🎾',
      home_conference: 'ACC',
      away_name: 'Duke',
      away_rank: 45,
      away_record: '13-12',
      away_logo: '😈',
      away_conference: 'ACC',
      home_score: 0,
      away_score: 4,
      winner: 'away',
      stats_url: null,
      results_url: 'https://goduke.com/news/2026/4/15/mens-tennis-duke-opens-postseason-with-4-0-victory',
    },
    {
      id: 'today-5',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Virginia Tech',
      home_rank: null,
      home_record: null,
      home_logo: '🎾',
      home_conference: 'ACC',
      away_name: 'North Carolina',
      away_rank: 46,
      away_record: '13-10',
      away_logo: '🐏',
      away_conference: 'ACC',
      home_score: 0,
      away_score: 4,
      winner: 'away',
      stats_url: null,
      results_url: 'https://goheels.com/news/2026/4/15/mens-tennis-mten-acc-recap-vs-virginia-tech',
    },
    {
      id: 'today-6',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'California',
      home_rank: 47,
      home_record: '14-12',
      home_logo: '🐻',
      home_conference: 'ACC',
      away_name: 'Georgia Tech',
      away_rank: 57,
      away_record: '12-12',
      away_logo: '🐝',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 0,
      winner: 'home',
      stats_url: null,
      results_url: 'https://calbears.com/news/2026/4/15/mens-tennis-cal-tops-georgia-tech-in-round-1-of-the-acc-championships.aspx',
    },
    {
      id: 'today-7',
      gender: 'men',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Florida State',
      home_rank: 60,
      home_record: '12-14',
      home_logo: '🔶',
      home_conference: 'ACC',
      away_name: 'Louisville',
      away_rank: 62,
      away_record: '17-12',
      away_logo: '🔴',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 1,
      winner: 'home',
      stats_url: null,
      results_url: 'https://seminoles.com/news/2026/4/15/mens-tennis-seminoles-defeat-no-62-louisville-in-acc-opening-match',
    },
  ];

  // ── Men's Recent Results ─────────────────────────────────────────────────
  // [id, match_date, home_name, away_name, home_score, away_score, winner, conference]
  const menRecentRaw = [
    ['r-1',  'Apr 12, 2026', 'Ohio State',    'Washington',      4, 0, 'home', 'BigTen'],
    ['r-2',  'Apr 12, 2026', 'TCU',           'Baylor',          4, 1, 'home', 'Big12'],
    ['r-3',  'Apr 12, 2026', 'Mississippi State', 'Alabama',     5, 2, 'home', 'SEC'],
    ['r-4',  'Apr 12, 2026', 'Oklahoma',      'Texas A&M',       4, 1, 'home', 'Big12'],
    ['r-5',  'Apr 12, 2026', 'Arizona',       'Oklahoma State',  4, 0, 'home', 'Pac-12'],
    ['r-6',  'Apr 12, 2026', 'Georgia',       'Auburn',          4, 0, 'home', 'SEC'],
    ['r-7',  'Apr 12, 2026', 'South Carolina','Tennessee',       4, 0, 'home', 'SEC'],
    ['r-8',  'Apr 12, 2026', 'UCF',           'Arizona State',   4, 3, 'home', 'Big12'],
    ['r-9',  'Apr 12, 2026', 'USC',           'Illinois',        4, 1, 'home', 'BigTen'],
    ['r-10', 'Apr 12, 2026', 'San Diego',     'Pepperdine',      4, 1, 'home', 'WCC'],
    ['r-11', 'Apr 12, 2026', 'Stanford',      'California',      4, 2, 'home', 'ACC'],
    ['r-12', 'Apr 12, 2026', 'Florida',       'Arkansas',        4, 1, 'home', 'SEC'],
    ['r-13', 'Apr 12, 2026', 'UCLA',          'Northwestern',    4, 0, 'home', 'BigTen'],
    ['r-14', 'Apr 12, 2026', 'Ole Miss',      'Kentucky',        4, 3, 'home', 'SEC'],
    ['r-15', 'Apr 12, 2026', 'Columbia',      'Princeton',       4, 0, 'home', 'Ivy'],
    ['r-16', 'Apr 12, 2026', 'Cornell',       'Penn',            4, 3, 'home', 'Ivy'],
    ['r-17', 'Apr 12, 2026', 'Harvard',       'Yale',            6, 1, 'home', 'Ivy'],
    ['r-18', 'Apr 11, 2026', 'Wake Forest',   'NC State',        4, 0, 'home', 'ACC'],
    ['r-19', 'Apr 11, 2026', 'Illinois',      'UCLA',            4, 2, 'home', 'BigTen'],
    ['r-20', 'Apr 11, 2026', 'Michigan',      'Michigan State',  4, 2, 'home', 'BigTen'],
    ['r-21', 'Apr 11, 2026', 'Notre Dame',    'Louisville',      4, 0, 'home', 'ACC'],
    ['r-22', 'Apr 11, 2026', 'Duke',          'North Carolina',  4, 1, 'home', 'ACC'],
    ['r-23', 'Apr 11, 2026', 'Miami (FL)',    'Florida State',   4, 3, 'home', 'ACC'],
    ['r-24', 'Apr 10, 2026', 'Texas',         'Florida',         4, 1, 'home', 'Big12'],
    ['r-25', 'Apr 10, 2026', 'LSU',           'Kentucky',        4, 1, 'home', 'SEC'],
    ['r-26', 'Apr 10, 2026', 'Oklahoma',      'Arkansas',        4, 0, 'home', 'Big12'],
    ['r-27', 'Apr 10, 2026', 'Georgia',       'South Carolina',  4, 1, 'home', 'SEC'],
    ['r-28', 'Apr 10, 2026', 'Auburn',        'Ole Miss',        4, 3, 'home', 'SEC'],
    ['r-29', 'Apr 10, 2026', 'Vanderbilt',    'Alabama',         4, 0, 'home', 'SEC'],
    ['r-30', 'Apr 9, 2026',  'TCU',           'Oklahoma State',  4, 0, 'home', 'Big12'],
    ['r-31', 'Apr 9, 2026',  'Virginia',      'Virginia Tech',   4, 0, 'home', 'ACC'],
    ['r-32', 'Apr 9, 2026',  'Arizona',       'UCF',             4, 1, 'home', 'Pac-12'],
  ];

  const menRecent = menRecentRaw.map(([id, match_date, home_name, away_name, home_score, away_score, winner, conference]) => ({
    id,
    gender: 'men',
    match_date,
    round: null,
    status: 'final',
    home_name,
    home_rank: null,
    home_record: null,
    home_logo: '🎾',
    home_conference: conference,
    away_name,
    away_rank: null,
    away_record: null,
    away_logo: '🎾',
    away_conference: conference,
    home_score,
    away_score,
    winner,
    stats_url: null,
    results_url: null,
  }));

  // ── Women's Today (Apr 15, 2026) ─────────────────────────────────────────
  const womenToday = [
    {
      id: 'w-live-1',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'SEC Regular Season',
      status: 'final',
      home_name: 'Alabama',
      home_rank: 55,
      home_record: '12-14',
      home_logo: '🐘',
      home_conference: 'SEC',
      away_name: 'Mississippi State',
      away_rank: 47,
      away_record: '15-9',
      away_logo: '🐶',
      away_conference: 'SEC',
      home_score: 0,
      away_score: 0,
      winner: null,
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-1',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'SEC Regular Season',
      status: 'final',
      home_name: 'LSU',
      home_rank: 15,
      home_record: '16-8',
      home_logo: '🐯',
      home_conference: 'SEC',
      away_name: 'Missouri',
      away_rank: null,
      away_record: null,
      away_logo: '🎾',
      away_conference: 'SEC',
      home_score: 4,
      away_score: 0,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-2',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'SEC Regular Season',
      status: 'final',
      home_name: 'Arkansas',
      home_rank: 54,
      home_record: '16-9',
      home_logo: '🐗',
      home_conference: 'SEC',
      away_name: 'South Carolina',
      away_rank: 27,
      away_record: '18-6',
      away_logo: '🐔',
      away_conference: 'SEC',
      home_score: 4,
      away_score: 3,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-3',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'Big 12',
      status: 'final',
      home_name: 'Texas Tech',
      home_rank: 31,
      home_record: '17-6',
      home_logo: '🔴',
      home_conference: 'Big12',
      away_name: 'Houston',
      away_rank: 41,
      away_record: '16-7',
      away_logo: '🔴',
      away_conference: 'Big12',
      home_score: 4,
      away_score: 1,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-4',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Stanford',
      home_rank: 33,
      home_record: '14-8',
      home_logo: '🌲',
      home_conference: 'ACC',
      away_name: 'Virginia Tech',
      away_rank: null,
      away_record: null,
      away_logo: '🎾',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 2,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-5',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'Big 12',
      status: 'final',
      home_name: 'BYU',
      home_rank: 37,
      home_record: '15-6',
      home_logo: '🔵',
      home_conference: 'Big12',
      away_name: 'Utah',
      away_rank: 35,
      away_record: '16-5',
      away_logo: '🔴',
      away_conference: 'Big12',
      home_score: 4,
      away_score: 2,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-6',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'SEC Regular Season',
      status: 'final',
      home_name: 'Ole Miss',
      home_rank: 38,
      home_record: '16-5',
      home_logo: '🔴',
      home_conference: 'SEC',
      away_name: 'Kentucky',
      away_rank: null,
      away_record: null,
      away_logo: '🎾',
      away_conference: 'SEC',
      home_score: 4,
      away_score: 0,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-7',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Notre Dame',
      home_rank: 44,
      home_record: '17-7',
      home_logo: '☘️',
      home_conference: 'ACC',
      away_name: 'Boston College',
      away_rank: 61,
      away_record: '13-10',
      away_logo: '🦅',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 2,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-8',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Wake Forest',
      home_rank: 63,
      home_record: '12-12',
      home_logo: '🎩',
      home_conference: 'ACC',
      away_name: 'Syracuse',
      away_rank: null,
      away_record: null,
      away_logo: '🎾',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 1,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
    {
      id: 'wt-9',
      gender: 'women',
      match_date: 'Apr 15, 2026',
      round: 'ACC Championship — R1',
      status: 'final',
      home_name: 'Florida State',
      home_rank: null,
      home_record: null,
      home_logo: '🎾',
      home_conference: 'ACC',
      away_name: 'Georgia Tech',
      away_rank: 64,
      away_record: '11-12',
      away_logo: '🐝',
      away_conference: 'ACC',
      home_score: 4,
      away_score: 2,
      winner: 'home',
      stats_url: null,
      results_url: null,
    },
  ];

  // ── Women's Recent Results ───────────────────────────────────────────────
  const womenRecentRaw = [
    ['wr-1',  'Apr 12, 2026', 'Auburn',        'Vanderbilt',    4, 0, 'home', 'SEC'],
    ['wr-2',  'Apr 12, 2026', 'Ohio State',    'Indiana',       4, 0, 'home', 'BigTen'],
    ['wr-3',  'Apr 12, 2026', 'North Carolina','Florida State', 4, 0, 'home', 'ACC'],
    ['wr-4',  'Apr 12, 2026', 'Virginia',      'NC State',      4, 2, 'home', 'ACC'],
    ['wr-5',  'Apr 12, 2026', 'USC',           'Illinois',      4, 1, 'home', 'BigTen'],
    ['wr-6',  'Apr 12, 2026', 'Florida',       'Missouri',      4, 0, 'home', 'SEC'],
    ['wr-7',  'Apr 12, 2026', 'Michigan',      'Rutgers',       4, 0, 'home', 'BigTen'],
    ['wr-8',  'Apr 12, 2026', 'Duke',          'Miami (FL)',    4, 2, 'home', 'ACC'],
    ['wr-9',  'Apr 12, 2026', 'UCLA',          'Northwestern',  4, 1, 'home', 'BigTen'],
    ['wr-10', 'Apr 12, 2026', 'UCF',           'West Virginia', 4, 2, 'home', 'Big12'],
    ['wr-11', 'Apr 12, 2026', 'Washington',    'Wisconsin',     4, 1, 'home', 'BigTen'],
    ['wr-12', 'Apr 12, 2026', 'Clemson',       'Syracuse',      4, 1, 'home', 'ACC'],
    ['wr-13', 'Apr 12, 2026', 'SMU',           'Stanford',      4, 1, 'home', 'ACC'],
    ['wr-14', 'Apr 11, 2026', 'Georgia',       'Mississippi State', 4, 0, 'home', 'SEC'],
    ['wr-15', 'Apr 11, 2026', 'Texas A&M',     'Arkansas',      4, 0, 'home', 'SEC'],
    ['wr-16', 'Apr 11, 2026', 'Oklahoma',      'Texas',         4, 2, 'home', 'Big12'],
    ['wr-17', 'Apr 11, 2026', 'Tennessee',     'LSU',           4, 3, 'home', 'SEC'],
    ['wr-18', 'Apr 11, 2026', 'Arizona State', 'Utah',          4, 0, 'home', 'Big12'],
    ['wr-19', 'Apr 11, 2026', 'Michigan',      'Maryland',      4, 0, 'home', 'BigTen'],
    ['wr-20', 'Apr 11, 2026', 'Virginia',      'NC State',      4, 2, 'home', 'ACC'],
    ['wr-21', 'Apr 10, 2026', 'Auburn',        'Missouri',      4, 0, 'home', 'SEC'],
    ['wr-22', 'Apr 10, 2026', 'North Carolina','Miami (FL)',    4, 3, 'home', 'ACC'],
    ['wr-23', 'Apr 10, 2026', 'Duke',          'Florida State', 4, 0, 'home', 'ACC'],
    ['wr-24', 'Apr 10, 2026', 'Florida',       'Vanderbilt',    4, 0, 'home', 'SEC'],
    ['wr-25', 'Apr 10, 2026', 'USC',           'Northwestern',  4, 1, 'home', 'BigTen'],
    ['wr-26', 'Apr 10, 2026', 'Virginia',      'Wake Forest',   4, 0, 'home', 'ACC'],
    ['wr-27', 'Apr 9, 2026',  'Georgia',       'Alabama',       4, 0, 'home', 'SEC'],
    ['wr-28', 'Apr 9, 2026',  'Oklahoma',      'Texas A&M',     4, 1, 'home', 'Big12'],
    ['wr-29', 'Apr 9, 2026',  'Texas',         'Arkansas',      4, 0, 'home', 'Big12'],
    ['wr-30', 'Apr 9, 2026',  'LSU',           'Kentucky',      4, 1, 'home', 'SEC'],
    ['wr-31', 'Apr 9, 2026',  'Tennessee',     'Ole Miss',      4, 1, 'home', 'SEC'],
  ];

  const womenRecent = womenRecentRaw.map(([id, match_date, home_name, away_name, home_score, away_score, winner, conference]) => ({
    id,
    gender: 'women',
    match_date,
    round: null,
    status: 'final',
    home_name,
    home_rank: null,
    home_record: null,
    home_logo: '🎾',
    home_conference: conference,
    away_name,
    away_rank: null,
    away_record: null,
    away_logo: '🎾',
    away_conference: conference,
    home_score,
    away_score,
    winner,
    stats_url: null,
    results_url: null,
  }));

  const allMatches = [...menToday, ...menRecent, ...womenToday, ...womenRecent];
  for (const m of allMatches) {
    await upsertMatch(pool, m);
  }
  console.log(`Seeded ${allMatches.length} matches.`);
}

// ---------------------------------------------------------------------------
// Rankings
// ---------------------------------------------------------------------------

async function seedRankings(pool) {
  // Delete all then re-insert so ranks stay canonical.
  await pool.query(`DELETE FROM rankings`);

  const menRankings = [
    [1,  'Texas',           'Big12',  '21-6',  76.311],
    [2,  'Ohio State',      'BigTen', '25-3',  73.732],
    [3,  'TCU',             'Big12',  '19-5',  72.111],
    [4,  'Virginia',        'ACC',    '20-3',  70.761],
    [5,  'LSU',             'SEC',    '24-5',  68.868],
    [6,  'Mississippi State','SEC',   '20-4',  68.453],
    [7,  'Wake Forest',     'ACC',    '26-3',  66.541],
    [8,  'Oklahoma',        'Big12',  '18-5',  63.889],
    [9,  'Arizona',         'Pac-12', '20-3',  60.165],
    [10, 'Texas A&M',       'SEC',    '17-8',  57.762],
    [11, 'Baylor',          'Big12',  '20-8',  54.712],
    [12, 'Georgia',         'SEC',    '17-7',  52.834],
    [13, 'South Carolina',  'SEC',    '15-7',  49.915],
    [14, 'UCF',             'Big12',  '19-5',  46.980],
    [15, 'Illinois',        'BigTen', '20-6',  46.642],
    [16, 'San Diego',       'WCC',    '18-4',  44.078],
    [17, 'Stanford',        'ACC',    '16-7',  39.433],
    [18, 'Auburn',          'SEC',    '16-9',  39.420],
    [19, 'Florida',         'SEC',    '15-12', 39.366],
    [20, 'USC',             'BigTen', '16-6',  37.036],
    [21, 'UCLA',            'BigTen', '14-6',  36.211],
    [22, 'Vanderbilt',      'SEC',    '16-11', 36.180],
    [23, 'Michigan State',  'BigTen', '13-8',  35.666],
    [24, 'Notre Dame',      'ACC',    '20-6',  35.204],
    [25, 'Ole Miss',        'SEC',    '18-8',  34.872],
  ];

  const womenRankings = [
    [1,  'Georgia',         'SEC',    '17-4',  77.265],
    [2,  'Texas A&M',       'SEC',    '20-4',  75.074],
    [3,  'Auburn',          'SEC',    '29-3',  73.720],
    [4,  'Oklahoma',        'Big12',  '23-4',  71.804],
    [5,  'Ohio State',      'BigTen', '19-3',  71.558],
    [6,  'North Carolina',  'ACC',    '23-2',  70.307],
    [7,  'Virginia',        'ACC',    '19-4',  62.694],
    [8,  'Texas',           'Big12',  '16-6',  62.303],
    [9,  'Pepperdine',      'WCC',    '15-4',  57.657],
    [10, 'USC',             'BigTen', '17-5',  51.989],
    [11, 'Arizona State',   'Big12',  '19-4',  50.078],
    [12, 'Florida',         'SEC',    '15-6',  47.515],
    [13, 'NC State',        'ACC',    '19-7',  47.291],
    [14, 'Vanderbilt',      'SEC',    '19-8',  47.034],
    [15, 'LSU',             'SEC',    '16-8',  46.528],
    [16, 'Tennessee',       'SEC',    '13-8',  44.445],
    [17, 'Michigan',        'BigTen', '15-6',  43.497],
    [18, 'Duke',            'ACC',    '17-6',  42.476],
    [19, 'UCLA',            'BigTen', '13-6',  41.937],
    [20, 'UCF',             'Big12',  '18-3',  37.463],
    [21, 'California',      'ACC',    '11-6',  34.724],
    [22, 'Washington',      'BigTen', '17-3',  34.245],
    [23, 'TCU',             'Big12',  '17-4',  33.047],
    [24, 'Clemson',         'ACC',    '17-7',  30.541],
    [25, 'SMU',             'ACC',    '15-6',  28.958],
  ];

  for (const [rank, team_name, conference, record, points] of menRankings) {
    await pool.query(
      `INSERT INTO rankings (gender, rank, team_name, conference, record, points)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      ['men', rank, team_name, conference, record, points]
    );
  }

  for (const [rank, team_name, conference, record, points] of womenRankings) {
    await pool.query(
      `INSERT INTO rankings (gender, rank, team_name, conference, record, points)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      ['women', rank, team_name, conference, record, points]
    );
  }

  console.log(`Seeded ${menRankings.length} men's rankings and ${womenRankings.length} women's rankings.`);
}
